src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FilmRepository::class)]
class Film
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_de_sortie = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $duree = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'film')]
    private ?Realisateur $realisateur = null;

    #[ORM\ManyToMany(targetEntity: Genre::class, inversedBy: 'film')]
    private Collection $genres;

    #[ORM\ManyToMany(targetEntity: Acteur::class, inversedBy: 'film')]
    private Collection $acteurs;

    public function __construct()
    {
        $this->genres = new ArrayCollection();
        $this->acteurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDeSortie(): ?\DateTimeInterface
    {
        return $this->date_de_sortie;
    }

    public function setDateDeSortie(?\DateTimeInterface $date_de_sortie): self
    {
        $this->date_de_sortie = $date_de_sortie;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(?\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getRealisateur(): ?Realisateur
    {
        return $this->realisateur;
    }

    public function setRealisateur(?Realisateur $realisateur): self
    {
        $this->realisateur = $realisateur;

        return $this;
    }

    /**
     * @return Collection<int, Genre>
     */
    public function getGenres(): Collection
    {
        return $this->genres;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->genres->contains($genre)) {
            $this->genres->add($genre);
            $genre->addFilm($this);
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        if ($this->genres->removeElement($genre)) {
            $genre->removeFilm($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Acteur>
     */
    public function getActeurs(): Collection
    {
        return $this->acteurs;
    }

    public function addActeur(Acteur $acteur): self
    {
        if (!$this->acteurs->contains($acteur)) {
            $this->acteurs->add($acteur);
            $acteur->addFilm($this);
        }

        return $this;
    }

    public function removeActeur(Acteur $acteur): self
    {
        if ($this->acteurs->removeElement($acteur)) {
            $acteur->removeFilm($this);
        }

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre')
            ->add('description')
            ->add('date_de_sortie', null, [
                'format' => 'dd MMMM yyyy',
                'years' => range(1930, 2023)
                ])
            ->add('duree')
            ->add('image')
            ->add('realisateur')
            ->add('genres')
            ->add('acteurs')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Film;
use App\Form\FilmType;
use App\Repository\FilmRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/film')]
class FilmController extends AbstractController
{
    // méthode affichant tout les films
    // utilise un param converter (FilmRepository $filmRepository)
    // ce qui nous evite de devoir aller chercher manuellement les film en bdd
    #[Route('/', name: 'app_film_index', methods: ['GET'])]
    public function index(FilmRepository $filmRepository): Response
    {
        return $this->render('film/index.html.twig', [
            'films' => $filmRepository->findAll(),
        ]);
    }

    // route permettant l'ajout des films
    #[Route('/new', name: 'app_film_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FilmRepository $filmRepository): Response
    {
        // on instancie un objet de type film
        $film = new Film();
        // on crée le formulaire en allant chercher le builder dans le dossier form et en l'associant à l'objet precedent
        $form = $this->createForm(FilmType::class, $film);
        // on récupère le formulaire
        $form->handleRequest($request);

        // dans le cas ou le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {

            // dans le cas ou il n'y a pas d'exception levées
            try {
                // on va chercher la methode save du repository film pour enregistrement en base de données
                $filmRepository->save($film, true);
                // redirection vers la page affichage des films
                return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
                // dans le cas ou une exception est levée
            } catch (\Exception $e) {
                // on affiche un message en haut de la page du formulaire
                $this->addFlash('error', "le formulaire n'est pas valide");
            }
        }

        return $this->render('film/new.html.twig', [
            'form' => $form,
        ]);
    }

    // route permettant l'afficher un film par son id
    // utilise un param converter (Film $film = null)
    // on le met a null par defaut pour eviter la levée d'exception si l'id n'existe pas en bdd
    #[Route('/{id}', name: 'app_film_show', methods: ['GET'])]
    public function show(Film $film = null): Response
    {
        // si l'id n'existe pas on affiche un message et une redirection
        if($film == null) {
            $this->flash("le film n'existe pas");
        }

        return $this->render('film/show.html.twig', [
            'film' => $film,
        ]);
    }

    // route permettant la mise a jour d'un film
    // on utilise un param converter ( Film $film = null)
    // doctrine sait quand créer et quand modifier, il repère si la clé primaire est renseignée
    // si oui, il modifie l'objet, si non il crée l'objet
    #[Route('/{id}/edit', name: 'app_film_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Film $film = null, FilmRepository $filmRepository): Response
    {
        // dans le cas ou l'id n'existe pas
        if($film == null) {
            return $this->flash("le film n'existe pas");
        }

        $form = $this->createForm(FilmType::class, $film);
        $form->handleRequest($request);

        // on vérifie si le formulaire est valide
        if ($form->isSubmitted() && $form->isValid()) {
            // méthode permettant soit de créer, soit de mettre à jour, en fonction de si l'id est renseignée
            $filmRepository->save($film, true);

            return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('film/edit.html.twig', [
            'film' => $film,
            'form' => $form,
        ]);
    }

    // route permettant la suppression
    // utilise un param converter pour récupérer l'objet en bdd
    #[Route('/{id}', name: 'app_film_delete', methods: ['POST'])]
    public function delete(Request $request, Film $film = null, FilmRepository $filmRepository): Response
    {
        // si l'id n'existe pas
        if($film == null) {
           $this->flash("l'id n'existe pas");
        }

        // si j'ai les droits pour supprimer
        if ($this->isCsrfTokenValid('delete' . $film->getId(), $request->request->get('_token'))) {
            $filmRepository->remove($film, true);
        }

        // redirection apres la suppression
        return $this->redirectToRoute('app_film_index', [], Response::HTTP_SEE_OTHER);
    }

    // methode privée permettant de gérer les messages flash
    // prend en paramètre le message à afficher dans twig
    private function flash($message): Response {
        $this->addFlash('error', $message);
        return $this->redirectToRoute('app_film_index');
    }
}

templates/film/_delete_form.html.twig
<form method="post" action="{{ path('app_film_delete', {'id': film.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ film.id) }}">
    <button class="btn btn-warning">Delete</button>
</form>

templates/film/_form.html.twig
{{ form_start(form) }}
    {# {{ form_widget(form) }} #}
    <div class="row">
        <div class="mb-3 col">
            {{ form_row(form.titre) }}
        </div>

        <div class="mb-3 col">
            {{ form_row(form.description) }}
        </div>
    </div>

    {{ form_row(form.genres) }}
    <div>
    </div>
    {# <select class="form-select" multiple>
        <option value="">
            {{ form_row(form.genres) }}
        </option>
    </select> #}
    {{ form_rest(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
</div>

templates/film/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Film{% endblock %}

{% block body %}
    <h1>Edit Film</h1>

    {{ include('film/_form.html.twig', {'button_label': 'Update'}) }}
    <div class="d-flex justify-content-around">
        <a href="{{ path('app_film_index') }}" class="btn btn-info">back to list</a>
        {{ include('film/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/film/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film accueil{% endblock %}

{% block body %}
    <div class="container ">
        <h1 class="text-center my-3">Film accueil</h1>


        <div class="row ">
        {% for item in films %}
            <div class="card col-4 m-2" style="width: 15rem;">
                <img src="{{ item.image }}" class="card-img-top" alt="affiche">
                <div class="card-body">
                    <h5 class="card-title">{{item.titre}}</h5>
                    
                    <a href="{{ path('app_film_edit', {'id': item.id}) }}" class="btn btn-primary">Edition</a>
                    <a href="{{ path('app_film_show', {'id': item.id}) }}" class="btn btn-primary">Detail</a>
                </div>
            </div>
        {% endfor %}
        </div>
        <a class="btn btn-info" href="{{ path('app_film_new') }}">Create new</a>
    </div>
{% endblock %}

templates/film/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Film{% endblock %}

{% block body %}
    <h1>Create new Film</h1>

    {# Message error #}


    {{ include('film/_form.html.twig') }}

    <a class="btn btn-info" href="{{ path('app_film_index') }}">back to list</a>
{% endblock %}

templates/film/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film{% endblock %}

{% block body %}
    <h1 class="text-center">{{ film.titre }}</h1>

    {# <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ film.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ film.titre }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ film.description }}</td>
            </tr>
            <tr>
                <th>Date_de_sortie</th>
                <td>{{ film.dateDeSortie ? film.dateDeSortie|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ film.duree ? film.duree|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ film.image }}</td>
            </tr>
        </tbody>
    </table> #}
    <div class="d-flex justify-content-center ">
        <div class="card col-4 m-2" style="width: 15rem;">
            <img src="{{ film.image }}" class="card-img-top" alt="affiche">
            <div class="card-body">
                <h5 class="card-title text-center">{{film.titre}}</h5>
                <p>{{ film.description }}</p>
                <div class="d-flex justify-content-around">
                    <a href="{{ path('app_film_edit', {'id': film.id}) }}" class="btn btn-primary">Edition</a>
                    {{ include('film/_delete_form.html.twig') }}
                </div>
                
            </div>
        </div>
    </div>
    <a href="{{ path('app_film_index') }}" class="btn btn-primary">back to list</a>

{% endblock %}